package:
    name: odenlls
    version: "0.1.0"

source:
    path: ./dist/ODEnlls-0.1.0.tar.gz
    sha256: 72a2a60eb65e61b61bbb31a9fa5a905385e122eda2e4fe1c608d06b104853378 

requirements:
    build: 
        - python
    run:
        - python
        - numpy >=1.13.3
        - scipy >=1.0.0
        - pandas >=0.21.1
        - matplotlib >=2.1.1

test:
    import:
        - ODEnlls
